### PR TITLE
Update library to 889ec27

### PR DESCRIPTION
**Pull request by BrettMichaelJohnson**

### CODE REVIEW

**Comment by wiarlawd** [comment]
Why do this without waiting for full group feeds?

**Comment by BrettMichaelJohnson** [comment]
FS doesn't feed groups

**Comment by wiarlawd** [comment]
I'll continue to guess why you're doing this, then. The rule is to not update plexi in connectors that are not under active development, to reduce the risk if we need to release a patch or customers build from master. The only outstanding task for FS that I know of, given your reminder, is the params for access time et al. That's not worth updating plexi on master at this point.

**Comment by BrettMichaelJohnson** [comment]
I have active branches in FS for params and force.  They have been sitting there for a month.  I just wanted to check them in.  I'll leave abandon this.

**Pull request closed without merging**
